messages/Controllers/MessageModuleController.cs
using System.Web.Mvc;

namespace ticonet.Controllers
{
    public class MessageModuleController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

messages/Controllers/Ng/FiltersController.cs
using Business_Logic.MessagesModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ticonet.Controllers.Ng.ViewModels;
using ticonet.ParentControllers;
using Ninject;
using Business_Logic.SqlContext;

namespace ticonet.Controllers.Ng {

    public class FiltersController : NgController<FilterVM> {
        ISqlLogic sqllogic;

        [Inject]
        public FiltersController(ISqlLogic logic) {
            sqllogic = logic;
        }

        protected override NgResult _create(FilterVM[] models) {
            throw new NotImplementedException();
        }

        protected override NgResult _delete(FilterVM[] models) {
            throw new NotImplementedException();
        }

        protected override FetchResult<FilterVM> _fetch(int? Skip, int? Count, NgControllerInstruct[] filters) {
            IEnumerable<FilterVM> filts;
            int allQueryCount;
            using (var l = new MessagesModuleLogic()) {
                var result = l.GetFiltered<tblFilter>(Skip, Count, filters, out allQueryCount);
                filts = result.Select(x => PocoConstructor.MakeFromObj(x, sqllogic, FilterVM.tblFilterPR)).ToArray();
            }

            return FetchResult<FilterVM>.Succes(filts, allQueryCount);
        }

        protected override NgResult _update(FilterVM[] models) {
            throw new NotImplementedException();
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public JsonResult GetOperatorsForType(string typename) {
            if (string.IsNullOrWhiteSpace(typename))
                return NgResultToJsonResult(NgResult.Fail("Typename is undefined"));
            var items = SqlOperator.GetAllowedForSqlType(typename);
            return NgResultToJsonResult(FetchResult<SqlOperator>.Succes(items, items.Count()));
        }
    }
}

messages/Controllers/Ng/RfiltersController.cs
using Business_Logic.MessagesModule;
using Business_Logic.MessagesModule.EntitiesExtensions;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ticonet.Controllers.Ng.ViewModels;
using ticonet.ParentControllers;

namespace ticonet.Controllers.Ng {
    public class RfiltersController : NgController<RFilterVM> {
        protected override NgResult _create(RFilterVM[] models) {
            //TODO OPTIMIZE
            using (var l = new MessagesModuleLogic()) {
                foreach (var model in models) {
                    var filt = l.Create<tblRecepientFilter>();
                    filt.Name = model.Name;
                    filt.tblRecepientFilterTableNameId = model.BaseTableId;
                    l.Add(filt);
                    model.Id = filt.Id;
                    CreateAndUpdateRFilterParts(model, l);
                }
            }
            return NgResult.Succes();
        }


        protected override NgResult _update(RFilterVM[] models) {
            using (var l = new MessagesModuleLogic()) {
                foreach (var model in models) {
                    var filt = l.Get<tblRecepientFilter>(model.Id);
                    filt.Name = model.Name;
                    filt.tblRecepientFilterTableNameId = model.BaseTableId;
                    l.SaveChanges(filt);
                    model.Id = filt.Id;
                    CreateAndUpdateRFilterParts(model, l);
                }
            }
            return NgResult.Succes();
        }

        protected void ManagerRFilterPart<TEnitity,TNgViewModel> (MessagesModuleLogic l, IEnumerable<TNgViewModel> items, Action<TEnitity,TNgViewModel> updater) 
            where TEnitity: class,IMessagesModuleEntity
            where TNgViewModel: class,INgViewModel
        {
            if (items == null) return;
            //TODO OPTIMIZE work with DB
            foreach (var item in items) {
                TEnitity ent = null;
                if (item.ng_ToDelete)
                    l.Delete<TEnitity>(item.Id);
                else if (item.ng_JustCreated)
                    ent = l.Create<TEnitity>();
                else
                    ent = l.Get<TEnitity>(item.Id);
                if (ent != null) {
                    updater(ent, item);
                    if (item.ng_JustCreated)
                        l.Add(ent);
                    else
                        l.SaveChanges(ent);
                }
            }
        }

        protected void CreateAndUpdateRFilterParts (RFilterVM model, MessagesModuleLogic l) {
            //!!!! IMPLEMENT POCO_AUTOBINDING MECHANISM IF YOU GOING TO DO SAME THINGS IN OTHER PLACE
            ManagerRFilterPart<tblFilter, FilterVM>(l, model.filters, (e, m) => {
                e.Key = m.Key;
                e.Name = m.Name;
                e.autoUpdatedList = m.autoUpdatedList;
                if (!m.autoUpdatedList){
                    string[] ops = new string[m.ValsOps.Length];
                    string[] vals = new string[m.ValsOps.Length];
                    for (int i = 0; i < m.ValsOps.Length; i++) {
                        ops[i] = m.ValsOps[i].Operator;
                        vals[i] = m.ValsOps[i].Value == null ? "": m.ValsOps[i].Value.ToString();
                    }
                    e.OperatorsJSON = JsonConvert.SerializeObject(ops);
                    e.ValuesJSON = JsonConvert.SerializeObject(vals);
                }
                else {
                    e.OperatorsJSON = "[]";
                    e.ValuesJSON = "[]";
                }
                e.allowMultipleSelection = m.allowMultipleSelection;
                e.allowUserInput = m.allowUserInput;
                e.Type = m.Type;
                e.tblRecepientFilterId = model.Id;
            });

            //!!!! IMPLEMENT POCO_AUTOBINDING MECHANISM IF YOU GOING TO DO SAME THINGS IN OTHER PLACE
            ManagerRFilterPart<tblWildcard, WildcardVM>(l, model.wildcards, (e, m) => {
                e.Name = m.Name;
                e.Key = m.Key;
                e.Code = m.Code;
                e.tblRecepientFilterId = model.Id;
            });

            //!!!! IMPLEMENT POCO_AUTOBINDING MECHANISM IF YOU GOING TO DO SAME THINGS IN OTHER PLACE
            ManagerRFilterPart<tblRecepientCard, RecepientcardVM>(l, model.reccards, (e, m) => {
                e.Name = m.Name;
                e.NameKey = m.NameKey;
                e.PhoneKey = m.PhoneKey;
                e.EmailKey = m.EmailKey;
                e.tblRecepientFilterId = model.Id;
            });

        }

        protected override NgResult _delete(RFilterVM[] models) {
            throw new NotImplementedException();
        }

        protected override FetchResult<RFilterVM> _fetch(int? Skip, int? Count, NgControllerInstruct[] filters) {
            using (var l = new MessagesModuleLogic()) {
                var items = l.GetAll<tblRecepientFilter>()
                    .Select(x => PocoConstructor.MakeFromObj(x,RFilterVM.tblRecepientFilterPR));
                return FetchResult<RFilterVM>.Succes(items,items.Count());
            }
        }

    }
}

messages/Controllers/Ng/TemplatesController.cs
using System;
using System.Linq;
using ticonet.ParentControllers;
using ticonet.Controllers.Ng.ViewModels;
using Business_Logic.MessagesModule;
using System.Web.Mvc;
using Ninject;
using Business_Logic.SqlContext;
using Business_Logic.MessagesModule.Mechanisms;
using Business_Logic.MessagesModule.DataObjects;

namespace ticonet.Controllers.Ng{

    [Authorize]
    public class TemplatesController : NgController<TemplateVM> {
        ISqlLogic sqllogic;

        [Inject]
        public TemplatesController(ISqlLogic logic) {
            sqllogic = logic;
        }

        protected override NgResult _create(TemplateVM[] models) {
            using (var l = new MessagesModuleLogic()) {
                foreach (var model in models) {
                    var item = l.Create<tblTemplate>();
                    TemplateVM.ReflectToTblTemplate.Run(model, item);
                    l.Add(item);
                }
            }
            return NgResult.Succes(models.Count() + " new templates was added");
        }

        protected override NgResult _delete(TemplateVM[] models) {
            using (var l = new MessagesModuleLogic()) {
                foreach (var model in models) {
                    l.Delete<tblTemplate>(model.Id);
                }
            }
            return NgResult.Succes(models.Count() + " templates was removed");
        }

        protected override FetchResult<TemplateVM> _fetch(int? Skip, int? Count, NgControllerInstruct[] filters) {
            using (var l = new MessagesModuleLogic()) {
                var queryResult = l.GetAll<tblTemplate>()
                    .Select(x => PocoConstructor.MakeFromObj(x, TemplateVM.tblTemplatePR));
                return FetchResult<TemplateVM>.Succes(queryResult,queryResult.Count());
            }
        }

        protected override NgResult _update(TemplateVM[] models) {
            using (var l = new MessagesModuleLogic()) {
                foreach (var model in models) {
                    var item = l.Get<tblTemplate>(model.Id);
                    TemplateVM.ReflectToTblTemplate.Run(model, item);
                    l.SaveChanges(item);
                }
            }
            return NgResult.Succes(models.Count() + " templates was modified");
        }

        string ToStringSafe(object obj){
            if (obj == null)
                return "";
            return obj.ToString();
        }

        public JsonResult MockMessage (int templateId, int? MaxCount) {
            using (var l = new MessagesModuleLogic()) {
                var tmpl = l.Get<tblTemplate>(templateId);
                if (tmpl == null)
                    return NgResultToJsonResult(NgResult.Fail("Server Error: cannot find template, try save it and re-open."));

                var items = TASK_PROTOTYPE.GetDemoMessages(l,tmpl,sqllogic,tmpl.IsSms, MaxCount ?? 0);
                return NgResultToJsonResult(FetchResult<Message>.Succes(items, items.Count));
            }
        }
    }
}

messages/Controllers/Ng/WildcardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ticonet.Controllers.Ng.ViewModels;
using Business_Logic.MessagesModule;
using ticonet.ParentControllers;

namespace ticonet.Controllers.Ng
{
    public class WildcardsController : NgController<WildcardVM> {
        protected override NgResult _create(WildcardVM[] models) {
            throw new NotImplementedException();
        }

        protected override NgResult _delete(WildcardVM[] models) {
            throw new NotImplementedException();
        }

        protected override FetchResult<WildcardVM> _fetch(int? Skip, int? Count, NgControllerInstruct[] filters) {
            using (var l = new MessagesModuleLogic()) {
                int fullQueryCount;
                var queryResult = l.GetFiltered<tblWildcard>(Skip, Count, filters, out fullQueryCount)
                    .Select(x => PocoConstructor.MakeFromObj(x, WildcardVM.tblWildcardPR));
                return FetchResult<WildcardVM>.Succes(queryResult, fullQueryCount);
            }
        }

        protected override NgResult _update(WildcardVM[] models) {
            throw new NotImplementedException();
        }
    }
}

messages/Views/MessageModule/Index.cshtml
<!DOCTYPE html>
@{
    Layout = "";
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Message Module</title>
    @Styles.Render("~/bundles/MessagesModule")
    <link href="~/Content/AwaitLayer.css" rel="stylesheet" />
    <link href="~/Content/CodeArea.css" rel="stylesheet" />
    <link href="~/Content/MessageModule_PrototypeStyles.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,300i,400,400i,700" rel="stylesheet">
</head>
<body>

    <div class="main-container" ng-app="App" ng-cloak>

        <!--HoveringNotifications Controller-->
        <div ng-controller="NotificationController" data-ng-init="init()">
            <div class="notification-container">
                <div class="ngan-fade-mid" ng-repeat="msg in va.Messages | orderBy: '+created'">
                    <div ng-click="CloseMsg(msg)" class="notification notification-{{msg.type.nclass}} move-near">
                        <div class="notification-text">
                            <div>
                                <span class="notification-glyphicon glyphicon glyphicon-{{msg.type.glicon}}"></span>
                                <span class="notification-header">
                                    {{msg.header}}
                                </span>
                            </div>
                            <div>
                                <pre class="reset-pre">{{msg.body}}</pre>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--Page blocks Controller-->
        <div ng-controller="MessageModulePageController" data-ng-init="init()">
            <!--Await-Layer-->
            <div class="await-layer" ng-if="holdview">
                <div class="floatingBarsIndicator">
                    <div class="blockG" id="rotateG_01"></div>
                    <div class="blockG" id="rotateG_02"></div>
                    <div class="blockG" id="rotateG_03"></div>
                    <div class="blockG" id="rotateG_04"></div>
                    <div class="blockG" id="rotateG_05"></div>
                    <div class="blockG" id="rotateG_06"></div>
                    <div class="blockG" id="rotateG_07"></div>
                    <div class="blockG" id="rotateG_08"></div>
                </div>
            </div>

            <!--Everything Under Await-Layer-->
            <div class="main-layer" ng-class="{'blured':holdview}">

                <!--Page Header-->
                <div class="main-block" style="background: #333333">
                    <div class="txt-s-huge">
                        <i style="padding:0 10px" 
                           class="glyphicon glyphicon-cog iconclick" 
                           ng-click="va.showSettings=!va.showSettings">
                        </i> Mailing Module
                    </div>
                </div>
                
                <!--Page Body-->

                <!-- Settings Window MOCK -->
                <div class="settings-window ngan-fade-mid txt-c-grmore" ng-if="va.showSettings">
                    <div class="txt-s-huge txt-c-base">
                        Settings
                    </div>
                    <div class="txt-s-med txt-c-gr bot-bord">
                        Mail service
                    </div>
                    <div>sender adress</div>
                    <div>port...</div>
                    <div class="txt-s-med txt-c-gr bot-bord">
                        Sms service
                    </div>
                    <div>sender adress</div>
                    <div>...</div>
                </div>

                <!-- Stored Filters -->
                <div class="main-block bot-bord" ng-class="{'unfolded': !va.filters_folded}">
                    <span class="txt-s-big">
                        <a class="asimple" ng-click="va.filters_folded=!va.filters_folded">
                            <i ng-class="{'turn90': !va.filters_folded}" class="rotable glyphicon glyphicon-play"></i>
                        </a>
                        Stored Filters
                    </span>

                    <div class="unfold-block" ng-if="!va.filters_folded">
                        @Html.Partial("_ngMFilters")
                    </div>

                </div>

                <!-- Templates -->
                <div class="main-block bot-bord" ng-class="{'unfolded': !va.templates_folded}">
                    <span class="txt-s-big">
                        <a class="asimple" ng-click="va.templates_folded=!va.templates_folded">
                            <i ng-class="{'turn90': !va.templates_folded}" class="rotable glyphicon glyphicon-play"></i>
                        </a>
                        Templates
                    </span>

                    <div class="unfold-block" ng-if="!va.templates_folded">
                        @Html.Partial("_ngTemplates")
                    </div>

                </div>

                <!-- Schedules -->
                <div class="main-block bot-bord" ng-class="{'unfolded': !va.mails_folded}">
                    <span class="txt-s-big">
                        <a class="asimple" ng-click="va.mails_folded=!va.mails_folded">
                            <i ng-class="{'turn90': !va.mails_folded}" class="rotable glyphicon glyphicon-play"></i>
                        </a>
                        Schedules
                    </span>
                    <div class="unfold-block" ng-if="!va.mails_folded">
                        @Html.Partial("_ngSchedules")
                    </div>
                </div>

                <!-- Reports -->
                <div class="main-block bot-bord" ng-class="{'unfolded': !va.reports_folded}">
                    <span class="txt-s-big">
                        <a class="asimple" ng-click="va.reports_folded=!va.reports_folded">
                            <i ng-class="{'turn90': !va.reports_folded}" class="rotable glyphicon glyphicon-play"></i>
                        </a>
                        Reports
                    </span>

                    <div class="unfold-block" ng-if="!va.filters_folded">
                        @Html.Partial("_ngTemplates")
                    </div>

                </div>

            </div>

        </div>


    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/AngularApp")
    @*@RenderSection("scripts", required: false)*@
</body>
</html>

messages/Views/MessageModule/_ngReports.cshtml
<div>

</div>

messages/Views/MessageModule/_ngTemplates.cshtml
<div ng-controller="TemplatesController"
     data-ng-init="init({
        urls: {
            gettemplates: '@Url.Action("Fetch","Templates")',
            mngtemplates: '@Url.Action("Manage","Templates")',
            getwildcards: '@Url.Action("Fetch","Wildcards")',
            getmfilters: '@Url.Action("Fetch","Rfilters")',
            getfilters: '@Url.Action("Fetch","Filters")',
            mockmsgs: '@Url.Action("MockMessage","Templates")',
            getreservedcards: '@Url.Action("GetReservedCodes","RecepientCards")',
            getreccards: '@Url.Action("Fetch","RecepientCards")',
        }
    })">

    <!-- Enumeration -->
    <div class="col-xs-3 enum-container">
        <a ng-click="templCreate()"> create new </a>
        <div ng-repeat="templ in va.templates | orderBy: 'Name'">
            <span class="txt-c-gr">
                <a class="iconclick padd-hor-t" ng-click="templEdit(templ)">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
                <a class="iconclick padd-hor-t" ng-click="templDelete(templ)">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
                <i class="glyphicon txt-c-green padd-hor-t"
                   ng-class="templ.IsSms ? 'glyphicon-comment' : 'glyphicon-envelope'"></i>
                <span class="padd-hor-t txt-c-gr txt-anim" ng-class="{'txt-accent':templ.Id===va.curtemplate.Id}">
                    {{templ.Name}}
                </span>
            </span>
        </div>
    </div>

    <!-- Editor -->
    <div class="col-xs-9">
        <div class="editor-container" ng-if="va.curtemplate!==null">
            <!--Name -->
            <div>
                <input class="txtinput-big txt-s-med" style="width:320px" type="text" 
                       ng-model="va.curtemplate.Name" />
            </div>
            <!--Base on RFilter-->
            <div>
                <span class="txt-c-grmore">Based on Filter:</span>
                <div ng-repeat="mfilt in va.metafilters">
                    <div class="txt-c-gr">
                        <span class="txt-anim hover-highlight txt-c-gr clickable" ng-click="setMFilt(mfilt)">
                            <i class="glyphicon iconclick"
                               ng-class="va.curtemplate.RecepientFilterId===mfilt.Id ? 'glyphicon-check txt-c-gr' : 'glyphicon-unchecked'"></i>
                            <span>{{mfilt.Name}}</span>
                        </span>
                    </div>
                </div>
            </div>
            <!--Type (sms or email) -->
            <div>
                <span class="txt-c-grmore clickable" ng-click="va.curtemplate.IsSms=!va.curtemplate.IsSms">
                    <i ng-class="va.curtemplate.IsSms ? 'glyphicon-check txt-c-gr' : 'glyphicon-unchecked'" class="glyphicon iconclick"></i> sms
                    <i ng-class="!va.curtemplate.IsSms ? 'glyphicon-check txt-c-gr' : 'glyphicon-unchecked'" class="glyphicon iconclick"></i> mail
                </span>
            </div>

            <!--Filters-->
            <div class="top-bord bot-bord">
                <div ng-repeat="nfilt in va.filters">
                    <div class="txt-c-gr txt-anim hover-highlight clickable" ng-click="nfilt.Show=!nfilt.Show">
                        <i class="glyphicon glyphicon-filter"></i>
                        {{nfilt.Name}}
                    </div>
                    <div ng-if="nfilt.Show" class="ngan-fade-mid" style="padding-left:15px">

                        <!--For direct input-->
                        <div ng-if="nfilt.ValsOps.length===1&&!nfilt.autoUpdatedList">
                       
                            <span class="txt-c-gr">{{nfilt.Key}} {{nfilt.ValsOps[0].Operator}}</span>
                            <input placeholder="..." class="txtinput" 
                                   type="{{InputType(nfilt.Type)}}" 
                                   ng-model="GetFilterValueCont(nfilt).Values[0]" 
                                   ng-model-options="{timezone: '+0000'}"/>
                        </div>

                        <!--For list choose-->
                        <div ng-if="nfilt.ValsOps.length>1||nfilt.autoUpdatedList">
                            <div ng-repeat="valop in nfilt.ValsOps">
                                <span class="txt-anim hover-highlight txt-c-gr clickable" ng-click="SwitchFilterValueContVal(nfilt,$index)">
                                    <i class="glyphicon iconclick"
                                       ng-class="HasFilterValueContVal(nfilt,valop.Value) ? 'glyphicon-check txt-c-gr' : 'glyphicon-unchecked txt-c-grmore'"></i>
                                    <span>{{nfilt.Key}} {{valop.Operator}} {{valop.Value}}</span>
                                </span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!--Header -->
            <div>
                <span class="txt-c-grmore" style="padding-right:10px">Header: </span>
                <input class="txtinput" type="text" ng-model="va.curtemplate.MsgHeader"
                       placeholder="..."
                       droppable id="{{va.templatesHeader_ElemId}}"
                       drop="templatesTextDropped"
                       style="width:320px" />
            </div>

            <div class="clearfix">
                <div class="col-xs-6 no-padding">

                    <!--Message -->
                    <div id="codearea" class="textarea-highlighted-container" data-ng-init="InitCodeArea('codearea')">
                        <div class="textareabackdrop">
                            <div class="highlights"></div>
                        </div>
                        <textarea class='textarea-highlighted txtarea'
                                    ng-change="HandleCodeArea()"
                                    ng-model="va.curtemplate.MsgBody"
                                    droppable id="{{va.templatesBody_ElemId}}"
                                    drop="templatesTextDropped">
                        </textarea>
                    </div>
                    <!--SendTo-->
                    <div>
                        <span class="txt-s-med txt-c-gr">Send to Recepient Groups:</span>
                        <div ng-repeat="rc in va.reccards">
                            <div class="txt-c-gr">
                                <span class="txt-anim hover-highlight txt-c-gr clickable" ng-click="SwitchReccard(rc)">
                                    <i class="glyphicon iconclick"
                                       ng-class="HasReccard(rc) ? 'glyphicon-check txt-c-gr' : 'glyphicon-unchecked'"></i>
                                    <span>{{rc.Name}}</span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <!--Widlcards-->
                    <div>
                        <span class="txt-s-med txt-c-gr">Wildcards</span>
                        <div class="bounded-block-m">
                            <div ng-repeat="wcard in va.wildcards">
                                <span class="txt-c-gr txt-anim hover-highlight"
                                      draggableclass="wildcard" draggable id="wildcard_{{wcard.Id}}">
                                    <i class="glyphicon glyphicon-fire"></i>
                                    {{wcard.Name}}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--Save/Cancel-->
            <div>
                <a class="abut" ng-click="templSave()">Save</a>
                <a class="abut" ng-click="hideEditor()">Cancel</a>
            </div>
            <div>
                <a class="abut" ng-click="DEMO()">Save and Get Demo Messages</a>
                <hr />
                <div ng-repeat="msg in va.demomsgs">
                    <div>{{msg.Header}}</div>
                    <div>{{msg.Adress}}</div>
                    <div><pre>{{msg.Body}}</pre></div>
                    <hr />
                </div>
            </div>
        </div>
    </div>
</div>